Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleCRM.Data;
using SimpleCRM.Models;
using SimpleCRM.ViewModels;

namespace SimpleCRM.Controllers
{
    [Authorize]
    public class CampaignController : Controller
    {
        private readonly ApplicationDbContext context;
        public CampaignController (ApplicationDbContext dbcontext)
        {
            context = dbcontext;
        }
        public IActionResult Index()
        {
            List<Campaign> campaigns = context.Campaigns.ToList();
            return View(campaigns);
        }

        public IActionResult Add()
        {
            AddCampaignViewModel addCampaignViewModel = new AddCampaignViewModel();
            return View(addCampaignViewModel);
        }


        [HttpPost]
        public IActionResult Add(AddCampaignViewModel addCampaignViewModel)
        {
            if (ModelState.IsValid)
            {
                Campaign newCampaign = new Campaign()
                {
                    ID = addCampaignViewModel.ID,
                    CampaignCode = addCampaignViewModel.CampaignCode,
                    CampaignDescription = addCampaignViewModel.CampaignDescription,
                    CampaignMonth = addCampaignViewModel.CampaignMonth,
                    CampaignYear = addCampaignViewModel.CampaignYear

                };
                context.Campaigns.Add(newCampaign);
                context.SaveChanges();
                return Redirect("/Campaign");
            }
            return View(addCampaignViewModel);
        }

        public IActionResult Search ()
        {
            return View();
        }

        public IActionResult ViewCampaign(string campaignCode)
        {
            Campaign Campaign = context.Campaigns.SingleOrDefault(c => c.CampaignCode == campaignCode);
            /*List<Transactions> gifts = context
                .Transactions
                .Include(gift => gift.TAmount)
                .Where(c => c.TCampaign == campaignCode)
                .ToList();*/
            ViewCampaignViewModel viewCampaignViewModel = new ViewCampaignViewModel
            {
                Campaign = Campaign//,
                //Gifts = gifts
            };
            return View(viewCampaignViewModel);
        }

    }
}

Controllers/DonorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleCRM.Models;
using SimpleCRM.ViewModels;
using SimpleCRM.Data;

namespace SimpleCRM.Controllers
{
    [Authorize]
    public class DonorController : Controller
    {
        private readonly ApplicationDbContext context;
        public DonorController(ApplicationDbContext dbcontext)
        {
            context = dbcontext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            AddDonorViewModel addDonorViewModel = new AddDonorViewModel();
            return View(addDonorViewModel);
        }


        [HttpPost]
        public IActionResult Add(AddDonorViewModel addDonorViewModel)
        {
            if (ModelState.IsValid)
            {
                Donor newDonor = new Donor()
                {
                    Name = addDonorViewModel.Name,
                    Address = addDonorViewModel.Address,
                    City = addDonorViewModel.City,
                    State = addDonorViewModel.State,
                    Zip = addDonorViewModel.Zip
                };
                context.Donors.Add(newDonor);
                context.SaveChanges();
                TempData["message"] = "Donor added to database";
                return Redirect("/Donor/Add");
            }
            return View();
        }
    }
}


       

Controllers/GiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimpleCRM.Models;
using SimpleCRM.ViewModels;
using SimpleCRM.Data;

namespace SimpleCRM.Controllers
{
    [Authorize]
    public class GiftController : Controller
    {
        private readonly ApplicationDbContext context;
        public GiftController (ApplicationDbContext dbcontext)
        {
            context = dbcontext;
        }
        public IActionResult Index()
        {
            AddGiftViewModel addGiftViewModel = new AddGiftViewModel();
            return View(addGiftViewModel);
        }


        [HttpPost]
        public IActionResult Index(AddGiftViewModel addGiftViewModel)
        {
            

            if (ModelState.IsValid)
            {
                Transactions newTransaction = new Transactions()
                {
                    TDonor = addGiftViewModel.TDonor,
                    TYear = addGiftViewModel.currentYear,
                    TMonth = addGiftViewModel.currentMonth,
                    TDay = addGiftViewModel.currentDay,
                    TAmount = addGiftViewModel.TAmount,
                    TCampaign = addGiftViewModel.TCampaign
                };
                context.Transactions.Add(newTransaction);
                context.SaveChanges();
                TempData["message"] = "Gift posted to database";
                return Redirect("/Gift");
            }
            return View();
        }

        /*[AcceptVerbs("GET", "POST")]
        public IActionResult VerifyDonorID(int donorid)
        {
            if (SimpleCRM.Data.)
            //if (!Donor.VerifyDonorID(donorid))
                
            {
                return Json
            }
        }*/
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleCRM</title>

    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha384-R/oa7KS0iDoHwdh4Gyl3/fU7pgvSCt7oyuQ79pkw+e+bMWD9dzJJa+Zqd+XJS0AD" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleCRM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Donor" asp-action="Index">Donors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Campaign" asp-action="Index">Campaigns</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Gift" asp-action="Index">Gift Entry</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SimpleCRM 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>